# Generated by Django 5.2 on 2025-06-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('país', models.CharField(max_length=50)),
                ('temporada_actual', models.CharField(max_length=20)),
                ('logo', models.FileField(blank=True, null=True, upload_to='ligas')),
                ('reglamento', models.FileField(blank=True, null=True, upload_to='ligas')),
            ],
        ),
    ]
