# Generated by Django 5.2 on 2025-06-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liga',
            old_name='país',
            new_name='pais',
        ),
    ]
