# Generated by Django 5.2 on 2025-06-04 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('escudo', models.FileField(blank=True, null=True, upload_to='equipos')),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='equipos')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='Liga.liga')),
            ],
        ),
    ]
