# Generated by Django 5.2 on 2025-06-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0002_equipo_anios_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='anios_creacion',
        ),
    ]
