# Generated by Django 5.2 on 2025-06-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0003_remove_equipo_anios_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='anios_creacion',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
